/**
 *
 *  OrderItems.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "OrderItems.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::models
;

const std::string OrderItems::Cols::_id = "\"id\"";
const std::string OrderItems::Cols::_order_id = "\"order_id\"";
const std::string OrderItems::Cols::_plant_id = "\"plant_id\"";
const std::string OrderItems::Cols::_quantity = "\"quantity\"";
const std::string OrderItems::Cols::_price = "\"price\"";
const std::string OrderItems::primaryKeyName = "id";
const bool OrderItems::hasPrimaryKey = true;
const std::string OrderItems::tableName = "\"order_items\"";

const std::vector<typename OrderItems::MetaData> OrderItems::metaData_={
{"id","int32_t","integer",4,1,1,1},
{"order_id","int32_t","integer",4,0,0,0},
{"plant_id","int32_t","integer",4,0,0,0},
{"quantity","int32_t","integer",4,0,0,1},
{"price","std::string","numeric",0,0,0,1}
};
const std::string &OrderItems::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
OrderItems::OrderItems(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int32_t>(r["id"].as<int32_t>());
        }
        if(!r["order_id"].isNull())
        {
            orderId_=std::make_shared<int32_t>(r["order_id"].as<int32_t>());
        }
        if(!r["plant_id"].isNull())
        {
            plantId_=std::make_shared<int32_t>(r["plant_id"].as<int32_t>());
        }
        if(!r["quantity"].isNull())
        {
            quantity_=std::make_shared<int32_t>(r["quantity"].as<int32_t>());
        }
        if(!r["price"].isNull())
        {
            price_=std::make_shared<std::string>(r["price"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 5 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            orderId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            plantId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            quantity_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            price_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

OrderItems::OrderItems(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 5)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            orderId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            plantId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            quantity_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            price_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
}

OrderItems::OrderItems(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("order_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["order_id"].isNull())
        {
            orderId_=std::make_shared<int32_t>((int32_t)pJson["order_id"].asInt64());
        }
    }
    if(pJson.isMember("plant_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["plant_id"].isNull())
        {
            plantId_=std::make_shared<int32_t>((int32_t)pJson["plant_id"].asInt64());
        }
    }
    if(pJson.isMember("quantity"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["quantity"].isNull())
        {
            quantity_=std::make_shared<int32_t>((int32_t)pJson["quantity"].asInt64());
        }
    }
    if(pJson.isMember("price"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["price"].isNull())
        {
            price_=std::make_shared<std::string>(pJson["price"].asString());
        }
    }
}

void OrderItems::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 5)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            orderId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            plantId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            quantity_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            price_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
}

void OrderItems::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("order_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["order_id"].isNull())
        {
            orderId_=std::make_shared<int32_t>((int32_t)pJson["order_id"].asInt64());
        }
    }
    if(pJson.isMember("plant_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["plant_id"].isNull())
        {
            plantId_=std::make_shared<int32_t>((int32_t)pJson["plant_id"].asInt64());
        }
    }
    if(pJson.isMember("quantity"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["quantity"].isNull())
        {
            quantity_=std::make_shared<int32_t>((int32_t)pJson["quantity"].asInt64());
        }
    }
    if(pJson.isMember("price"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["price"].isNull())
        {
            price_=std::make_shared<std::string>(pJson["price"].asString());
        }
    }
}

const int32_t &OrderItems::getValueOfId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &OrderItems::getId() const noexcept
{
    return id_;
}
void OrderItems::setId(const int32_t &pId) noexcept
{
    id_ = std::make_shared<int32_t>(pId);
    dirtyFlag_[0] = true;
}
const typename OrderItems::PrimaryKeyType & OrderItems::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const int32_t &OrderItems::getValueOfOrderId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(orderId_)
        return *orderId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &OrderItems::getOrderId() const noexcept
{
    return orderId_;
}
void OrderItems::setOrderId(const int32_t &pOrderId) noexcept
{
    orderId_ = std::make_shared<int32_t>(pOrderId);
    dirtyFlag_[1] = true;
}
void OrderItems::setOrderIdToNull() noexcept
{
    orderId_.reset();
    dirtyFlag_[1] = true;
}

const int32_t &OrderItems::getValueOfPlantId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(plantId_)
        return *plantId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &OrderItems::getPlantId() const noexcept
{
    return plantId_;
}
void OrderItems::setPlantId(const int32_t &pPlantId) noexcept
{
    plantId_ = std::make_shared<int32_t>(pPlantId);
    dirtyFlag_[2] = true;
}
void OrderItems::setPlantIdToNull() noexcept
{
    plantId_.reset();
    dirtyFlag_[2] = true;
}

const int32_t &OrderItems::getValueOfQuantity() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(quantity_)
        return *quantity_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &OrderItems::getQuantity() const noexcept
{
    return quantity_;
}
void OrderItems::setQuantity(const int32_t &pQuantity) noexcept
{
    quantity_ = std::make_shared<int32_t>(pQuantity);
    dirtyFlag_[3] = true;
}

const std::string &OrderItems::getValueOfPrice() const noexcept
{
    static const std::string defaultValue = std::string();
    if(price_)
        return *price_;
    return defaultValue;
}
const std::shared_ptr<std::string> &OrderItems::getPrice() const noexcept
{
    return price_;
}
void OrderItems::setPrice(const std::string &pPrice) noexcept
{
    price_ = std::make_shared<std::string>(pPrice);
    dirtyFlag_[4] = true;
}
void OrderItems::setPrice(std::string &&pPrice) noexcept
{
    price_ = std::make_shared<std::string>(std::move(pPrice));
    dirtyFlag_[4] = true;
}

void OrderItems::updateId(const uint64_t id)
{
}

const std::vector<std::string> &OrderItems::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "order_id",
        "plant_id",
        "quantity",
        "price"
    };
    return inCols;
}

void OrderItems::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getOrderId())
        {
            binder << getValueOfOrderId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getPlantId())
        {
            binder << getValueOfPlantId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getQuantity())
        {
            binder << getValueOfQuantity();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getPrice())
        {
            binder << getValueOfPrice();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> OrderItems::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    return ret;
}

void OrderItems::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getOrderId())
        {
            binder << getValueOfOrderId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getPlantId())
        {
            binder << getValueOfPlantId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getQuantity())
        {
            binder << getValueOfQuantity();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getPrice())
        {
            binder << getValueOfPrice();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value OrderItems::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getOrderId())
    {
        ret["order_id"]=getValueOfOrderId();
    }
    else
    {
        ret["order_id"]=Json::Value();
    }
    if(getPlantId())
    {
        ret["plant_id"]=getValueOfPlantId();
    }
    else
    {
        ret["plant_id"]=Json::Value();
    }
    if(getQuantity())
    {
        ret["quantity"]=getValueOfQuantity();
    }
    else
    {
        ret["quantity"]=Json::Value();
    }
    if(getPrice())
    {
        ret["price"]=getValueOfPrice();
    }
    else
    {
        ret["price"]=Json::Value();
    }
    return ret;
}

std::string OrderItems::toString() const
{
    return toJson().toStyledString();
}

Json::Value OrderItems::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 5)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getOrderId())
            {
                ret[pMasqueradingVector[1]]=getValueOfOrderId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getPlantId())
            {
                ret[pMasqueradingVector[2]]=getValueOfPlantId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getQuantity())
            {
                ret[pMasqueradingVector[3]]=getValueOfQuantity();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getPrice())
            {
                ret[pMasqueradingVector[4]]=getValueOfPrice();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getOrderId())
    {
        ret["order_id"]=getValueOfOrderId();
    }
    else
    {
        ret["order_id"]=Json::Value();
    }
    if(getPlantId())
    {
        ret["plant_id"]=getValueOfPlantId();
    }
    else
    {
        ret["plant_id"]=Json::Value();
    }
    if(getQuantity())
    {
        ret["quantity"]=getValueOfQuantity();
    }
    else
    {
        ret["quantity"]=Json::Value();
    }
    if(getPrice())
    {
        ret["price"]=getValueOfPrice();
    }
    else
    {
        ret["price"]=Json::Value();
    }
    return ret;
}

bool OrderItems::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("order_id"))
    {
        if(!validJsonOfField(1, "order_id", pJson["order_id"], err, true))
            return false;
    }
    if(pJson.isMember("plant_id"))
    {
        if(!validJsonOfField(2, "plant_id", pJson["plant_id"], err, true))
            return false;
    }
    if(pJson.isMember("quantity"))
    {
        if(!validJsonOfField(3, "quantity", pJson["quantity"], err, true))
            return false;
    }
    else
    {
        err="The quantity column cannot be null";
        return false;
    }
    if(pJson.isMember("price"))
    {
        if(!validJsonOfField(4, "price", pJson["price"], err, true))
            return false;
    }
    else
    {
        err="The price column cannot be null";
        return false;
    }
    return true;
}
bool OrderItems::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                    const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err)
{
    if(pMasqueradingVector.size() != 5)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool OrderItems::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("order_id"))
    {
        if(!validJsonOfField(1, "order_id", pJson["order_id"], err, false))
            return false;
    }
    if(pJson.isMember("plant_id"))
    {
        if(!validJsonOfField(2, "plant_id", pJson["plant_id"], err, false))
            return false;
    }
    if(pJson.isMember("quantity"))
    {
        if(!validJsonOfField(3, "quantity", pJson["quantity"], err, false))
            return false;
    }
    if(pJson.isMember("price"))
    {
        if(!validJsonOfField(4, "price", pJson["price"], err, false))
            return false;
    }
    return true;
}
bool OrderItems::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                  const std::vector<std::string> &pMasqueradingVector,
                                                  std::string &err)
{
    if(pMasqueradingVector.size() != 5)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool OrderItems::validJsonOfField(size_t index,
                                  const std::string &fieldName,
                                  const Json::Value &pJson,
                                  std::string &err,
                                  bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
