name: plant-shop-haskell
version: 0.1.0
dependencies:
  - base >= 4.7 && < 5
  - aeson
  - scotty
  - postgresql-simple
  - wai-cors
  - jwt
  - text
  - random
  - containers
  - bytestring
  - scientific
  - directory
  - http-types
  - network
  - time
  - transformers
  - unliftio
  - wreq
  - wai-extra
  - aeson-casing
  - cookie
  - dotenv
  - cryptonite
  - memory

executables:
  plant-shop-haskell:
    main: Main.hs
    hs-source-dirs: src
