# Port par défaut (sera surchargé par le .env via DatabaseFactory/Main)
server.port=4100

# Désactiver le banner de démarrage
spring.main.banner-mode=off

# Configuration des logs (format simple)
logging.pattern.console=%d{HH:mm:ss} %-5p [%c{1.}] %m%n
