# Port par défaut (sera surchargé par le QuarkusBootstrap)
quarkus.http.port=4100

# Désactiver le banner de démarrage
quarkus.banner.enabled=false

# Désactiver Hibernate ORM, car nous gérons la connexion JDBC manuellement
quarkus.hibernate-orm.active=false

# Configuration des logs
quarkus.log.level=INFO
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] %s%e%n
