# Port par défaut (sera surchargé par le .env via Main)
server.port=4100

# Désactiver le banner de démarrage
spring.main.banner-mode=off

# Configuration des logs (format simple)
logging.pattern.console=%d{HH:mm:ss} %-5p [%c{1.}] %m%n

# Datasource par défaut (surchageable via variables ou config/.env)
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/plant_shop_java_spring_boot_security_hibernate}
spring.datasource.username=${DATABASE_USER:postgres}
spring.datasource.password=${DATABASE_PASS:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
