# Configuration du serveur HTTP
quarkus.http.port=4100
quarkus.http.host=0.0.0.0

# Configuration CORS
quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:4200
quarkus.http.cors.methods=GET,POST,PUT,DELETE,PATCH,OPTIONS
quarkus.http.cors.headers=*
quarkus.http.cors.exposed-headers=*
quarkus.http.cors.access-control-allow-credentials=true

# Configuration base de données PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/plant_shop_java_quarkus}
quarkus.datasource.username=${DATABASE_USER:postgres}
quarkus.datasource.password=${DATABASE_PASS:postgres}

# CDI
quarkus.arc.remove-unused-beans=false
quarkus.arc.dev-mode.monitoring-enabled=false

# Logging
quarkus.log.level=INFO
quarkus.log.console.enable=true
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] %s%e%n
