name: plant_shop_java_quarkus_microservices
dependencies:
  - io.quarkus:quarkus-arc:3.10.0
  - io.quarkus:quarkus-rest:3.10.0
  - io.quarkus:quarkus-vertx-http:3.10.0
  - io.quarkus:quarkus-netty:3.10.0
  - io.quarkus:quarkus-hibernate-orm:3.10.0
  - io.quarkus:quarkus-jdbc-mysql:3.10.0
  - io.quarkus:quarkus-narayana-jta:3.10.0
  - io.quarkus:quarkus-jackson:3.10.0
  - io.quarkus:quarkus-security:3.10.0
  - org.postgresql:postgresql:42.7.8
  - org.mindrot:jbcrypt:0.4
